"""Grounding enforcement -- the part that makes "numbers come from the API" a
guarantee rather than a promise in a prompt.

Two layers:

LAYER A (primary, correct by construction)
    fill_template() substitutes real weather values into an SOP's
    advice_template in pure Python. A number that reaches the user this way
    was never generated by a model at all.

LAYER B (for the synthesis step, which is free-form)
    validate_grounding() extracts every UNIT-TAGGED number from the composed
    text and checks each against the values actually returned by the API for
    this request, plus the thresholds of the policies that actually fired.
    Unit-tagging is what keeps this precise: "28.5 C", "45 km/h" and "70%" are
    weather claims and get checked; "SPF 50", "100 ml", "leave 30-45 min early"
    carry no weather unit and are correctly ignored as advice, not data.

Why thresholds are allowed alongside API values: several policies quote their
own trigger in their advice ("DO NOT CYCLE in 70%+ rain"). That 70 is ours --
it comes from sops_final_25.json, not from the model's imagination -- so
checking it against the API would produce a false violation. Both sources are
reported separately in the audit trail so a reviewer can always tell which
number came from where.
"""

import re

UNIT_TO_METRICS = {
    "c": ["temperature_2m", "temperature_2m_max", "temperature_2m_min", "apparent_temperature"],
    "km/h": ["wind_speed_10m", "wind_gusts_10m"],
    "%": ["precipitation_probability", "relative_humidity_2m"],
    "mm": ["precipitation", "precipitation_sum"],
    "cm": ["snowfall_sum"],
    "m": ["visibility"],
}

# Order matters: km/h, mm and cm must be tried before bare m.
#
# Two things here are load-bearing and were both found by testing, not by reading:
#
# 1. The (?<![\w.]) lookbehind stops us matching digits embedded in an
#    identifier. Without it, "wind_speed_10m = 38.0 km/h" reports a phantom
#    "10 m" claim, because the metric NAME contains a number then a unit letter.
#
# 2. The word boundary \b is attached to each ALPHABETIC unit individually,
#    not to the whole group. A trailing \b after the group silently breaks "%":
#    in "95% chance", the % is followed by a space, and two non-word characters
#    have no boundary between them, so the match fails and the claim is never
#    checked. That would let a fabricated "20% chance of rain" through while
#    the API said 95%. Percentages are half our weather claims, so this
#    mattered more than it looked.
_CLAIM_RE = re.compile(
    r"(?<![\w.])(\d+(?:\.\d+)?)\s*(°?\s*c\b|km/?h\b|%|mm\b|cm\b|m\b)",
    re.IGNORECASE,
)


def fill_template(template: str, weather_data: dict) -> str:
    """LAYER A: substitute real API values into {metric} placeholders."""
    merged = {**(weather_data.get("daily") or {}), **(weather_data.get("current") or {})}
    for key, value in merged.items():
        template = template.replace("{" + key + "}", str(value))
    return template


def extract_weather_claims(text: str) -> list[tuple[float, str]]:
    """Every (number, unit) pair in the text that looks like a weather claim."""
    claims = []
    for num, unit in _CLAIM_RE.findall(text):
        u = unit.lower().replace("°", "").replace(" ", "")
        u = {"kmh": "km/h"}.get(u, u)
        claims.append((float(num), u))
    return claims


def build_allowed_values(weather_data: dict, matched_sops: list[dict] | None = None) -> dict:
    """Allowed numbers per unit, from three traceable sources.

    1. "api"         -- values Open-Meteo returned for THIS request
    2. "thresholds"  -- the trigger values of the policies that actually fired
    3. "policy_text" -- unit-carrying numbers written into those policies'
                        own advice text

    Source 3 is necessary, not a loophole. Real policy guidance is full of
    numbers that carry weather units but are not measurements of today's
    weather: "Strong winds: 40-60 km/h gusts" (a description of the hazard
    class), "Temperature: 20-30C (comfortable)" (a comfort band), "core body
    temp below 35C" (body, not air), "Slow down (max 15-20 km/h)" (a cycling
    speed). Without source 3, the deterministic template fill in fill_template
    -- the thing that is correct by construction -- would fail this very
    validator, which would be incoherent.

    What the check still guarantees, which is the part that matters: the model
    cannot put a weather number in front of a user unless that number came
    from the live API or from our own policy file. It cannot invent one.
    """
    merged = {**(weather_data.get("daily") or {}), **(weather_data.get("current") or {})}

    allowed = {unit: {"api": [], "thresholds": [], "policy_text": []} for unit in UNIT_TO_METRICS}

    for unit, metrics in UNIT_TO_METRICS.items():
        allowed[unit]["api"] = [merged[m] for m in metrics if isinstance(merged.get(m), (int, float))]

        for sop in matched_sops or []:
            for key, value in (sop.get("values_used") or {}).items():
                if not key.startswith("threshold_"):
                    continue
                if key[len("threshold_"):] in metrics and isinstance(value, (int, float)):
                    allowed[unit]["thresholds"].append(value)

    for sop in matched_sops or []:
        template = sop.get("advice_template")
        if not template:
            continue
        for value, unit in extract_weather_claims(fill_template(template, weather_data)):
            if unit in allowed:
                allowed[unit]["policy_text"].append(value)

    return allowed


def trace_claims(text: str, weather_data: dict, matched_sops: list[dict] | None = None,
                 tol: float = 0.6) -> list[dict]:
    """Per-number provenance: where each weather claim in the text came from.

    This is what makes "why did it say 40 km/h?" answerable with a source
    rather than a shrug.
    """
    allowed = build_allowed_values(weather_data, matched_sops)
    merged = {**(weather_data.get("daily") or {}), **(weather_data.get("current") or {})}
    traced = []

    for value, unit in extract_weather_claims(text):
        permitted = allowed.get(unit)
        entry = {"value": value, "unit": unit, "source": None}

        if permitted:
            # Pick the CLOSEST metric, not merely the first within tolerance:
            # temperature_2m=14.7 and apparent_temperature=14.2 are both within
            # 0.6 of a cited "14.2 C", and attributing it to the wrong one
            # undermines the point of having a provenance trail at all.
            candidates = [
                (abs(value - merged[metric]), metric, merged[metric])
                for metric in UNIT_TO_METRICS[unit]
                if isinstance(merged.get(metric), (int, float)) and abs(value - merged[metric]) <= tol
            ]
            if candidates:
                _, metric, api_value = min(candidates)
                entry["source"] = f"live API: {metric}={api_value}"

            if entry["source"] is None and any(abs(value - t) <= tol for t in permitted["thresholds"]):
                entry["source"] = "policy threshold (a fired SOP's trigger value)"
            if entry["source"] is None and any(abs(value - p) <= tol for p in permitted["policy_text"]):
                entry["source"] = "policy advice text (written in sops_final_25.json)"

        traced.append(entry)
    return traced


def validate_grounding(text: str, weather_data: dict, matched_sops: list[dict] | None = None,
                       tol: float = 0.6) -> list[str]:
    """Returns a list of ungrounded claims. Empty list means fully grounded."""
    return [
        f"{c['value']}{c['unit']}"
        for c in trace_claims(text, weather_data, matched_sops, tol)
        if c["source"] is None
    ]


FRIENDLY_LABEL = {
    "temperature_2m": "temperature",
    "temperature_2m_max": "today's high",
    "temperature_2m_min": "today's low",
    "apparent_temperature": "feels like",
    "wind_speed_10m": "wind speed",
    "wind_gusts_10m": "wind gusts",
    "precipitation_probability": "chance of rain",
    "relative_humidity_2m": "humidity",
    "precipitation": "rain falling now",
    "precipitation_sum": "total rainfall today",
    "snowfall_sum": "snowfall today",
    "visibility": "visibility",
}


def whitelist_block(weather_data: dict, matched_sops: list[dict] | None = None) -> str:
    """The labelled block of numbers the composer is allowed to cite.

    Labels are human-readable on purpose: given raw field names, the model
    echoes them at the user ("precipitation_sum = 95.0 mm"), which reads like
    a database dump rather than advice.
    """
    merged = {**(weather_data.get("daily") or {}), **(weather_data.get("current") or {})}

    unit_label = {"c": "C", "km/h": "km/h", "%": "%", "mm": "mm", "cm": "cm", "m": "m"}
    lines = []
    for unit, metrics in UNIT_TO_METRICS.items():
        for metric in metrics:
            value = merged.get(metric)
            if isinstance(value, (int, float)):
                lines.append(f"  {FRIENDLY_LABEL.get(metric, metric)}: {value} {unit_label[unit]}")

    thresholds = []
    for sop in matched_sops or []:
        for key, value in (sop.get("values_used") or {}).items():
            if key.startswith("threshold_") and isinstance(value, (int, float)):
                thresholds.append(f"  {sop['id']} threshold: {key[len('threshold_'):]} = {value}")

    block = "LIVE WEATHER VALUES (the only weather numbers you may cite):\n" + "\n".join(lines)
    if thresholds:
        block += "\n\nPOLICY THRESHOLDS (you may cite these as thresholds):\n" + "\n".join(sorted(set(thresholds)))
    return block
